name: PlayerReport
version: 1.0.0
api: 5.0.0
author: NurAzliYT
main: NurAzliYT\PlayerReport\Main

commands:
  report:
    description: "Report a player"
    usage: "/report"
  viewreports:
    description: "View player reports"
    usage: "/viewreports"

config:
  settings:
    max_reports: 50
    
